### PR TITLE
Fix highlight paste

### PR DESCRIPTION
**Pull request by blms**
### What this PR does
- Per #198:
  - Highlights can be copied and pasted without error, and will carry their respective links
- Per #337:
  - Highlights / text will no longer disappear on color change
- Adds a loading indicator whenever document is being updated

### Additional notes

See https://github.com/performant-software/dm-2/pull/339#issuecomment-893693439 below.

### Status

- [ ] Reviewed
- [ ] Deployed

### Steps to test

1. Visit https://dm-2-staging.herokuapp.com/
2. Log in
3. Open or create a project with Write or Admin access
4. Open or create a document with highlights, and/or check it out and create some highlights

Issue #198:

5. Try to copy and paste one or more highlights, some that have links in them, some that don't
6. Verify that all of the highlights are pasted correctly with links copied successfully (note: a loading indicator may appear briefly)
7. Try steps 5 and 6 by copying from a checked-in document to a checked-out one

Issue #337:

8. Click the highlight selection tool
9. Select a highlight
10. Use the color tool to change its color and verify that it changes successfully (note: a loading indicator may appear briefly)
11. Create a new highlight in the document and repeat steps 8-10
11. Create a new text document and a highlight in that new document and repeat steps 8-10

### CODE REVIEW

**Comment by blms** [comment]
### Loading indicator

Since this PR introduces a loading indicator, it is up to @MartinFoys whether or not its appearance is acceptable. When editing highlights on a document, a loading indicator like this will appear on **all opened documents**:

https://user-images.githubusercontent.com/7234006/128403071-d81bab46-ab5d-4f85-96b2-f4c651eb58d9.mov

This is intended to prevent editing the document while backend transactions are occurring. It should prevent conflicts and other strange behavior.

It can get a bit slow if many, many highlights with many links are being copied. For example, this is what happens when copying and pasting this entire text:

https://user-images.githubusercontent.com/7234006/128403498-9c4cc8e3-f10a-4965-b0fa-04b3f31969ce.mov

This should be a rare occurrence, only when large numbers of highlights with many links are being edited all at once. But it is worth mentioning as a possibility.

**Comment by MartinFoys** [comment]
I am fine with this indicator - otherwise, what I've notice is that highlights paste in, but are not available or active or populated for a little bit of time - I imagine this indicator solves that too

**Comment by blms** [comment]
> I am fine with this indicator - otherwise, what I've noticed is that highlights paste in, but are not available or active or populated for a little bit of time - I imagine this indicator solves that too

Exactly! The intention is to make this clear to the end user, and prevent them from trying to make changes while that population is occurring.

**Review by jamiefolsom — APPROVED** [review]

**Comment by SteveMarvin** [comment]
Texts and links pasted within a document seem to work fine, but pasting into a new document does not seem to bring the links. It does however bring the colors, they just don't seem to have the associated links.

**Pull request merged**
